// vue-app/src/components/header-bar-brand.vue
<script>
export default {
  name: 'HeaderBarBrand',
};
</script>

<template>
  <div class="navbar-brand">
    <a
      class="navbar-item"
      href="https://vuejs.org/"
      target="_blank"
      rel="noopener noreferrer"
    >
      <i class="fab js-logo fa-vuejs fa-2x" aria-hidden="true" />
    </a>
    <router-link to="/" class="navbar-item nav-home">
      <span class="brand-first">SHOP</span>
      <span class="brand-second">AT</span>
      <span class="brand-third">HOME</span>
    </router-link>
  </div>
</template>

// react-app/src/components/HeaderBarBrand.js
import React from 'react';
import { NavLink } from 'react-router-dom';

const HeaderBarBrand = () => (
  <div className="navbar-brand">
    <a
      className="navbar-item"
      href="https://reactjs.org/"
      target="_blank"
      rel="noopener noreferrer"
    >
      <i className="fab js-logo fa-react fa-2x" aria-hidden="true" />
    </a>
    <NavLink to="/" className="navbar-item nav-home">
      <span className="brand-first">SHOP</span>
      <span className="brand-second">AT</span>
      <span className="brand-third">HOME</span>
    </NavLink>
  </div>
);

export default HeaderBarBrand;
