// angular-app/src/app/core/components/auth-login.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-auth-login',
  template: ` <div class="auth-link" (click)="goAuth()">{{ provider }}</div> `,
})
export class AuthLoginComponent {
  @Input() provider = '';

  goAuth() {
    const { pathname } = window.location;
    const redirect = `post_login_redirect_uri=${pathname}`;
    const url = `/.auth/login/${this.provider}?${redirect}`;
    window.location.href = url;
  }
}

// svelte-app/src/components/AuthLogin.svelte
<script lang="ts">
  export let provider = '';

  function goAuth() {
    const { pathname } = window.location;
    const redirect = `post_login_redirect_uri=${pathname}`;
    const url = `/.auth/login/${provider}?${redirect}`;
    window.location.href = url;
  }
</script>

<div class="auth-link" on:click={goAuth} on:keypress={goAuth}>{provider}</div>
