// react-app/src/products/ProductDetail.js
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { ButtonFooter, InputDetail } from '../components';

function ProductDetail({
  product: initProduct,
  handleCancelProduct,
  handleSaveProduct,
}) {
  const [product, setProduct] = useState(Object.assign({}, initProduct));
  const navigate = useNavigate();

  useEffect(() => {
    if (!product) {
      navigate('/products', { state: {} }); // no product, bail out of Details
    }
  }, [product]);

  function handleSave() {
    const chgProduct = { ...product, id: product.id || null };
    handleSaveProduct(chgProduct);
  }

  function handleNameChange(e) {
    setProduct({ ...product, name: e.target.value });
  }

  function handleDescriptionChange(e) {
    setProduct({ ...product, description: e.target.value });
  }

  function handleQuantityChange(e) {
    setProduct({ ...product, quantity: e.target.value });
  }

  return (
    <div className="card edit-detail">
      <header className="card-header">
        <p className="card-header-title">
          {product.name}
          &nbsp;
        </p>
      </header>
      <div className="card-content">
        <div className="content">
          {product.id && (
            <InputDetail name="id" value={product.id} readOnly="true" />
          )}
          <InputDetail
            name="name"
            value={product.name}
            placeholder="Oranges"
            onChange={handleNameChange}
          />
          <InputDetail
            name="description"
            value={product.description}
            placeholder="box"
            onChange={handleDescriptionChange}
          />
          <div className="field">
            <label className="label" htmlFor="quantity">
              quantity
            </label>
            <input
              name="quantity"
              className="input"
              type="number"
              min="1"
              max="100"
              defaultValue={product.quantity}
              placeholder="1"
              onChange={handleQuantityChange}
            />
          </div>
        </div>
      </div>
      <footer className="card-footer ">
        <ButtonFooter
          className="cancel-button"
          iconClasses="fas fa-undo"
          onClick={handleCancelProduct}
          label="Cancel"
        />
        <ButtonFooter
          className="save-button"
          iconClasses="fas fa-save"
          onClick={handleSave}
          label="Save"
        />
      </footer>
    </div>
  );
}

export default ProductDetail;

// svelte-app/src/products/ProductDetail.svelte
<script lang="ts">
  import { onMount, createEventDispatcher } from 'svelte';
  import { ButtonFooter } from '../components';
  import { Product } from '../models';

  const dispatch = createEventDispatcher();
  export let product: Product;
  let editingProduct = { ...product };

  onMount(() => watchProduct());

  function clear() {
    dispatch('unselect');
  }

  function saveProduct() {
    dispatch('save', editingProduct);
    clear();
  }

  function watchProduct() {
    if (product && product.id) {
      editingProduct = { ...product };
    } else {
      editingProduct = { id: undefined, name: '', description: '' };
    }
  }

  const cancelOptions = {
    className: 'card-footer-item cancel-button',
    label: 'Cancel',
    iconClasses: 'fas fa-undo',
  };

  const saveOptions = {
    className: 'card-footer-item save-button',
    label: 'Save',
    iconClasses: 'fas fa-save',
  };
</script>

<div class="card edit-detail">
  <header class="card-header">
    <p class="card-header-title">{editingProduct.name}</p>
  </header>
  <div class="card-content">
    <div class="content">
      {#if editingProduct.id}
        <div class="field">
          <label class="label" for="id">id</label>
          <input
            class="input"
            name="id"
            placeholder="99999"
            readonly
            type="text"
            bind:value={editingProduct.id} />
        </div>
      {/if}
      <div class="field">
        <label class="label" for="name">name</label>
        <input
          class="input"
          name="name"
          placeholder="Oranges"
          type="text"
          bind:value={editingProduct.name} />
      </div>
      <div class="field">
        <label class="label" for="description">description</label>
        <input
          class="input"
          name="description"
          placeholder="box"
          type="text"
          bind:value={editingProduct.description} />
      </div>
      <div class="field">
        <label class="label" for="quantity">quantity</label>
        <input
          class="input"
          name="quantity"
          placeholder="1"
          type="number"
          min="1"
          max="100"
          bind:value={editingProduct.quantity} />
      </div>
    </div>
  </div>

  <footer class="card-footer">
    <ButtonFooter {...cancelOptions} item={editingProduct} on:clicked={clear} />
    <ButtonFooter
      {...saveOptions}
      item={editingProduct}
      on:clicked={saveProduct} />
  </footer>
</div>
